# Generated by Django 6.1 on 2026-08-23 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_telefonico', models.CharField(blank=True, max_length=50, null=True)),
                ('identificador_externo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPO', 'Grupo')], default='INDIVIDUAL', max_length=50)),
                ('privacidad', models.CharField(choices=[('EMPRESARIAL', 'Empresarial'), ('PRIVADA', 'Privada'), ('SIN_CLASIFICAR', 'Sin Clasificar')], default='SIN_CLASIFICAR', max_length=50)),
                ('pendiente', models.BooleanField(db_index=True, default=False)),
                ('ultimo_mensaje_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_asignadas', to=settings.AUTH_USER_MODEL)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='comunicaciones.contacto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones', to='organizacion.sucursal')),
                ('usuarios_autorizados', models.ManyToManyField(blank=True, related_name='conversaciones_autorizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'permissions': [('cambiar_privacidad_conversacion', 'Can change conversation privacy classification')],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_externo', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('conversacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='grupo', to='comunicaciones.conversacion')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(choices=[('ENTRANTE', 'Entrante'), ('SALIENTE', 'Saliente'), ('SISTEMA', 'Sistema')], max_length=50)),
                ('tipo', models.CharField(choices=[('TEXT', 'Texto'), ('AUDIO', 'Audio'), ('IMAGE', 'Imagen'), ('VIDEO', 'Video'), ('DOCUMENT', 'Documento'), ('LOCATION', 'Ubicación'), ('CONTACT', 'Contacto'), ('REACTION', 'Reacción'), ('STICKER', 'Sticker'), ('UNKNOWN', 'Desconocido')], default='TEXT', max_length=50)),
                ('texto_original', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('LEIDO', 'Leído'), ('FALLIDO', 'Fallido')], default='RECIBIDO', max_length=50)),
                ('fecha_mensaje', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes', to='comunicaciones.conversacion')),
                ('remitente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_enviados', to='comunicaciones.contacto')),
                ('respuesta_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='comunicaciones.mensaje')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['fecha_mensaje'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='multimedia/')),
                ('identificador_externo', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_original', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=127)),
                ('size_bytes', models.IntegerField(blank=True, null=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_multimedia', to='comunicaciones.mensaje')),
            ],
            options={
                'verbose_name': 'Archivo Multimedia',
                'verbose_name_plural': 'Archivos Multimedia',
            },
        ),
        migrations.CreateModel(
            name='NumeroCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero_telefonico', models.CharField(blank=True, max_length=50, null=True)),
                ('identificador_externo', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('CORPORATIVO', 'Corporativo'), ('MIXTO', 'Mixto'), ('EXTERNO_PERSONAL', 'Externo Personal')], default='CORPORATIVO', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canales_propios', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canales', to='organizacion.sucursal')),
                ('sucursales_habilitadas', models.ManyToManyField(blank=True, related_name='canales_habilitados', to='organizacion.sucursal')),
                ('usuarios_autorizados', models.ManyToManyField(blank=True, related_name='canales_autorizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Número/Canal',
                'verbose_name_plural': 'Números/Canales',
            },
        ),
        migrations.AddField(
            model_name='conversacion',
            name='numero_canal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones', to='comunicaciones.numerocanal'),
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_administrador', models.BooleanField(default=False)),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membresias', to='comunicaciones.contacto')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='comunicaciones.grupo')),
            ],
            options={
                'verbose_name': 'Participante de Grupo',
                'verbose_name_plural': 'Participantes de Grupos',
            },
        ),
        migrations.CreateModel(
            name='IdentidadContactoExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=50)),
                ('identificador_externo', models.CharField(max_length=255)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identidades_externas', to='comunicaciones.contacto')),
            ],
            options={
                'verbose_name': 'Identidad Contacto Externa',
                'verbose_name_plural': 'Identidades Contactos Externas',
                'constraints': [models.UniqueConstraint(fields=('proveedor', 'identificador_externo'), name='unique_identidad_proveedor_externo')],
            },
        ),
        migrations.AddConstraint(
            model_name='mensaje',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('conversacion', 'external_id'), name='unique_external_id_per_conversation'),
        ),
        migrations.AddConstraint(
            model_name='conversacion',
            constraint=models.UniqueConstraint(condition=models.Q(('contacto__isnull', False), ('tipo', 'INDIVIDUAL')), fields=('numero_canal', 'contacto'), name='unique_conversacion_individual_por_contacto'),
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(fields=('grupo', 'contacto'), name='unique_contacto_per_grupo'),
        ),
    ]
