# Generated by Django 6.1 on 2026-08-23 21:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicaciones', '0001_initial'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivomultimedia',
            options={'verbose_name': 'Archivo multimedia', 'verbose_name_plural': 'Archivos multimedia'},
        ),
        migrations.AlterModelOptions(
            name='conversacion',
            options={'ordering': ['-ultimo_mensaje_at', '-created_at'], 'verbose_name': 'Conversación', 'verbose_name_plural': 'Conversaciones'},
        ),
        migrations.AlterModelOptions(
            name='identidadcontactoexterna',
            options={'verbose_name': 'Identidad externa del contacto', 'verbose_name_plural': 'Identidades externas de contactos'},
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['fecha_mensaje', 'pk'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='numerocanal',
            options={'ordering': ['-es_principal', 'nombre'], 'verbose_name': 'Número/Canal', 'verbose_name_plural': 'Números/Canales'},
        ),
        migrations.AlterModelOptions(
            name='participante',
            options={'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='identificador_externo',
        ),
        migrations.RemoveField(
            model_name='conversacion',
            name='asignado_a',
        ),
        migrations.RemoveField(
            model_name='conversacion',
            name='privacidad',
        ),
        migrations.RemoveField(
            model_name='conversacion',
            name='usuarios_autorizados',
        ),
        migrations.RemoveField(
            model_name='numerocanal',
            name='propietario',
        ),
        migrations.RemoveField(
            model_name='numerocanal',
            name='usuarios_autorizados',
        ),
        migrations.AddField(
            model_name='archivomultimedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='identidadcontactoexterna',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensaje',
            name='error_codigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='error_detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='numerocanal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numerocanal',
            name='es_principal',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='numerocanal',
            name='proveedor',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('OTRO', 'Otro')], db_index=True, default='WHATSAPP', max_length=50),
        ),
        migrations.AddField(
            model_name='numerocanal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='archivomultimedia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='multimedia/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='archivomultimedia',
            name='identificador_externo',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archivomultimedia',
            name='mime_type',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='archivomultimedia',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='archivomultimedia',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero_telefonico',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversaciones', to='organizacion.sucursal'),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='tipo',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('GRUPO', 'Grupo')], db_index=True, default='INDIVIDUAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='conversacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='comunicaciones.conversacion'),
        ),
        migrations.AlterField(
            model_name='identidadcontactoexterna',
            name='identificador_externo',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='identidadcontactoexterna',
            name='proveedor',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='direccion',
            field=models.CharField(choices=[('ENTRANTE', 'Entrante'), ('SALIENTE', 'Saliente'), ('SISTEMA', 'Sistema')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('LEIDO', 'Leído'), ('FALLIDO', 'Fallido')], db_index=True, default='PENDIENTE', max_length=50),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_mensaje',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='tipo',
            field=models.CharField(choices=[('TEXT', 'Texto'), ('AUDIO', 'Audio'), ('IMAGE', 'Imagen'), ('VIDEO', 'Video'), ('DOCUMENT', 'Documento'), ('LOCATION', 'Ubicación'), ('CONTACT', 'Contacto'), ('REACTION', 'Reacción'), ('STICKER', 'Sticker'), ('UNKNOWN', 'Desconocido')], db_index=True, default='TEXT', max_length=50),
        ),
        migrations.AlterField(
            model_name='numerocanal',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='numerocanal',
            name='identificador_externo',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='numerocanal',
            name='numero_telefonico',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='numerocanal',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='canales', to='organizacion.sucursal'),
        ),
        migrations.AlterField(
            model_name='numerocanal',
            name='tipo',
            field=models.CharField(choices=[('CORPORATIVO', 'Corporativo'), ('SUCURSAL', 'Sucursal'), ('ASESOR', 'Asesor'), ('OTRO', 'Otro')], db_index=True, default='CORPORATIVO', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='numerocanal',
            constraint=models.UniqueConstraint(condition=models.Q(('identificador_externo__isnull', False)), fields=('proveedor', 'identificador_externo'), name='unique_canal_proveedor_identificador'),
        ),
        migrations.AddConstraint(
            model_name='numerocanal',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True), ('es_principal', True)), fields=('proveedor',), name='unique_canal_principal_activo_proveedor'),
        ),
    ]
